// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction to Physical AI & Humanoid Robotics',
      items: ['physical-ai-intro/introduction'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Physics Simulation in Gazebo',
          items: [
            'module-2-digital-twin/chapter-1-gazebo/index',
            'module-2-digital-twin/chapter-1-gazebo/gazebo-setup-guide',
            'module-2-digital-twin/chapter-1-gazebo/diagrams-and-screenshots-guide',
            'module-2-digital-twin/chapter-1-gazebo/exercise-1-basic-robot',
            'module-2-digital-twin/chapter-1-gazebo/gazebo-plugins-examples',
            'module-2-digital-twin/chapter-1-gazebo/troubleshooting-guide',
            'module-2-digital-twin/chapter-1-gazebo/citations',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Visualization in Unity',
          items: [
            'module-2-digital-twin/chapter-2-unity/index',
            'module-2-digital-twin/chapter-2-unity/unity-installation-setup',
            'module-2-digital-twin/chapter-2-unity/robot-model-import-setup',
            'module-2-digital-twin/chapter-2-unity/material-lighting-setup',
            'module-2-digital-twin/chapter-2-unity/user-interface-controls',
            'module-2-digital-twin/chapter-2-unity/exercise-2-unity-visualization',
            'module-2-digital-twin/chapter-2-unity/diagrams-screenshots-guide',
            'module-2-digital-twin/chapter-2-unity/unity-ros-integration-examples',
            'module-2-digital-twin/chapter-2-unity/optimization-techniques',
            'module-2-digital-twin/chapter-2-unity/unity-documentation-citations',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Sensor Simulation',
          items: [
            'module-2-digital-twin/chapter-3-sensors/index',
            'module-2-digital-twin/chapter-3-sensors/lidar-simulation-tutorial',
            'module-2-digital-twin/chapter-3-sensors/depth-camera-simulation',
            'module-2-digital-twin/chapter-3-sensors/imu-simulation',
            'module-2-digital-twin/chapter-3-sensors/sensor-data-processing-ros',
            'module-2-digital-twin/chapter-3-sensors/exercise-3-sensor-simulation',
            'module-2-digital-twin/chapter-3-sensors/sensor-simulation-diagrams',
            'module-2-digital-twin/chapter-3-sensors/sensor-data-validation-comparison',
            'module-2-digital-twin/chapter-3-sensors/sensor-fusion-digital-twin',
            'module-2-digital-twin/chapter-3-sensors/sensor-simulation-research-citations',
          ],
        },
        'module-2-digital-twin/integration-guide',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Isaac Sim - Photorealistic Simulation',
          items: [
            'module-3-ai-robot-brain/chapter-1-isaac-sim/index',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/setup-guide',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/environment-creation',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/synthetic-data-generation',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/integration-examples',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/exercise-1',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/diagrams',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/code-examples',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/troubleshooting',
            'module-3-ai-robot-brain/chapter-1-isaac-sim/citations',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Isaac ROS - Hardware-Accelerated VSLAM',
          items: [
            'module-3-ai-robot-brain/chapter-2-isaac-ros/index',
            'module-3-ai-robot-brain/chapter-2-isaac-ros/setup-guide',
            'module-3-ai-robot-brain/chapter-2-isaac-ros/component-configuration',
            'module-3-ai-robot-brain/chapter-2-isaac-ros/vslam-implementation',
            'module-3-ai-robot-brain/chapter-2-isaac-ros/navigation-examples',
            'module-3-ai-robot-brain/chapter-2-isaac-ros/exercise-2',
            'module-3-ai-robot-brain/chapter-2-isaac-ros/diagrams',
            'module-3-ai-robot-brain/chapter-2-isaac-ros/code-examples',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Nav2 - Humanoid Path Planning',
          items: [
            'module-3-ai-robot-brain/chapter-3-nav2-humanoid/index',
            'module-3-ai-robot-brain/chapter-3-nav2-humanoid/setup-guide',
            'module-3-ai-robot-brain/chapter-3-nav2-humanoid/humanoid-config',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        {
          type: 'category',
          label: 'Chapter 1: Voice-to-Action - Using OpenAI Whisper',
          items: [
            'module-4-vla-educational-module/chapter-1-voice-to-action/index',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Cognitive Planning - LLMs to ROS 2 Actions',
          items: [
            'module-4-vla-educational-module/chapter-2-cognitive-planning/index',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Capstone Project - Autonomous Humanoid',
          items: [
            'module-4-vla-educational-module/chapter-3-capstone-project/index',
          ],
        },
      ],
    },
  ],
};

export default sidebars;